#!/usr/bin/env node
/**
 * StratumSS command line interface.
 *
 * `main()` returns a process exit code and never calls `process.exit()` itself,
 * so the watch mode can keep running and tests can drive it directly.
 */

import fs from 'fs';
import path from 'path';
import process from 'process';
import { fileURLToPath } from 'url';

import { parseArgs, HELP_TEXT, type CliOptions } from './args.js';
import { compile, formatDiagnostics, writeResult, type CompileOptions, type Diagnostic } from './compile.js';
import { listUtilityClasses } from './parser.js';
import { DEFAULT_EXTENSIONS, DEFAULT_IGNORED_DIRECTORIES, listFiles } from './scanner.js';

const FALLBACK_VERSION = '1.1.0';

/** Reads the version from package.json, falling back to the constant above. */
export function getVersion(): string {
    try {
        const here = path.dirname(fileURLToPath(import.meta.url));
        const manifest = path.join(here, '..', '..', 'package.json');
        const parsed = JSON.parse(fs.readFileSync(manifest, 'utf-8')) as { version?: string };
        return typeof parsed.version === 'string' ? parsed.version : FALLBACK_VERSION;
    } catch {
        return FALLBACK_VERSION;
    }
}

function formatBytes(bytes: number): string {
    if (bytes < 1000) return `${bytes} B`;
    if (bytes < 1000 * 1000) return `${(bytes / 1000).toFixed(1)} kB`;
    return `${(bytes / (1000 * 1000)).toFixed(2)} MB`;
}

function toCompileOptions(options: CliOptions): CompileOptions {
    return {
        sources: options.sources,
        allowUnknown: options.allowUnknown,
        minify: options.minify,
        extensions: options.extensions.length > 0 ? options.extensions : undefined,
        ignoredDirectories: [
            ...DEFAULT_IGNORED_DIRECTORIES,
            ...options.exclude
        ]
    };
}

function validateSources(sources: readonly string[]): string | null {
    for (const source of sources) {
        if (!fs.existsSync(source)) {
            return `Source path does not exist: ${source}`;
        }
    }
    return null;
}

function reportDiagnostics(diagnostics: readonly Diagnostic[], quiet: boolean): number {
    const errors = diagnostics.filter(diagnostic => diagnostic.level === 'error');
    const warnings = diagnostics.filter(diagnostic => diagnostic.level === 'warning');

    if (!quiet || errors.length > 0) {
        for (const line of formatDiagnostics([...errors, ...warnings])) {
            console.error(line);
        }
    }

    const summary: string[] = [];
    if (errors.length > 0) summary.push(`${errors.length} error${errors.length === 1 ? '' : 's'}`);
    if (warnings.length > 0) summary.push(`${warnings.length} warning${warnings.length === 1 ? '' : 's'}`);
    if (summary.length > 0) {
        console.error(`StratumSS found ${summary.join(' and ')}.`);
    }

    return errors.length;
}

interface BuildStats {
    files: number;
    classes: number;
    bytes: number;
    durationMs: number;
    output: string;
    errors: number;
    warnings: number;
}

function buildOnce(options: CliOptions, announce: boolean): BuildStats | null {
    const sourceError = validateSources(options.sources);
    if (sourceError !== null) {
        console.error(`error: ${sourceError}`);
        return null;
    }

    const compileOptions = toCompileOptions(options);
    const banner = `/*! StratumSS v${getVersion()} — generated by the StratumSS compiler. Do not edit. */`;
    const result = compile({ ...compileOptions, header: options.header ? banner : undefined });

    const errors = reportDiagnostics(result.diagnostics, options.quiet);
    const warnings = result.diagnostics.length - errors;

    if (errors > 0) {
        return null;
    }

    const output = path.resolve(options.output);
    writeResult(result, output);

    const stats: BuildStats = {
        files: result.files.length,
        classes: result.classes.length,
        bytes: Buffer.byteLength(result.css, 'utf-8'),
        durationMs: Math.round(result.durationMs * 100) / 100,
        output,
        errors,
        warnings
    };

    if (options.json) {
        console.log(JSON.stringify(stats, null, 2));
    } else if (!options.quiet && announce) {
        console.log(
            `StratumSS built ${stats.classes} utilities from ${stats.files} file${stats.files === 1 ? '' : 's'} ` +
            `into ${formatBytes(stats.bytes)} in ${stats.durationMs} ms`
        );
        console.log(`  output   ${path.relative(process.cwd(), stats.output) || stats.output}`);
        console.log(`  sources  ${options.sources.map(source => path.relative(process.cwd(), source) || '.').join(', ')}`);
    }

    return stats;
}

/** mtime snapshot of every scanned file; used when fs.watch is unavailable. */
function snapshotFiles(options: CliOptions): string {
    const files = listFiles(options.sources, toCompileOptions(options));
    const parts: string[] = [];

    for (const file of files) {
        try {
            const stats = fs.statSync(file);
            parts.push(`${file}:${stats.mtimeMs}:${stats.size}`);
        } catch {
            parts.push(`${file}:missing`);
        }
    }

    return parts.join('|');
}

/** Starts watching and returns a stop function. */
function watchSources(options: CliOptions, rebuild: () => void): () => void {
    let timer: NodeJS.Timeout | null = null;
    const schedule = (): void => {
        if (timer !== null) clearTimeout(timer);
        timer = setTimeout(() => {
            timer = null;
            rebuild();
        }, 120);
    };

    const watchers: fs.FSWatcher[] = [];

    try {
        for (const source of options.sources) {
            const stats = fs.statSync(source);
            const directory = stats.isDirectory() ? source : path.dirname(source);
            watchers.push(fs.watch(directory, { recursive: stats.isDirectory() }, schedule));
        }
        for (const watcher of watchers) {
            watcher.on('error', schedule);
        }
        return () => {
            for (const watcher of watchers) watcher.close();
            if (timer !== null) clearTimeout(timer);
        };
    } catch {
        // fs.watch is unavailable (some network filesystems, older kernels):
        // fall back to polling, which is slower but always works.
        watchers.forEach(watcher => watcher.close());
        let previous = snapshotFiles(options);
        const interval = setInterval(() => {
            const current = snapshotFiles(options);
            if (current !== previous) {
                previous = current;
                schedule();
            }
        }, 400);
        interval.unref?.();
        return () => {
            clearInterval(interval);
            if (timer !== null) clearTimeout(timer);
        };
    }
}

function runWatch(options: CliOptions): number {
    const first = buildOnce(options, true);
    if (first === null) {
        console.error('error: watch mode stopped because the initial build failed.');
        return 1;
    }

    const single = options.sources.length === 1;
    console.log(`Watching ${options.sources.length} source${single ? '' : 's'} for changes... (Ctrl+C to stop)`);

    const stop = watchSources(options, () => {
        const stats = buildOnce(options, false);
        if (stats === null) {
            console.error('error: rebuild failed; the previous stylesheet was left in place.');
            return;
        }
        console.log(`Rebuilt ${stats.classes} utilities → ${formatBytes(stats.bytes)} in ${stats.durationMs} ms`);
    });

    const shutdown = (): void => {
        stop();
        console.log('\nStopped watching.');
        process.exitCode = 0;
    };

    process.on('SIGINT', shutdown);
    process.on('SIGTERM', shutdown);

    return 0;
}

function runList(options: CliOptions): number {
    const entries = listUtilityClasses();

    if (options.json) {
        console.log(JSON.stringify(entries, null, 2));
        return 0;
    }

    const groups = new Map<string, string[]>();
    for (const entry of entries) {
        const list = groups.get(entry.group) ?? [];
        list.push(entry.className);
        groups.set(entry.group, list);
    }

    for (const [group, names] of groups) {
        console.log(`\n${group}`);
        for (const name of names) {
            console.log(`  ${name}`);
        }
    }

    console.log(`\n${entries.length} utilities across ${groups.size} groups.`);
    return 0;
}

/** Runs the CLI and returns the process exit code. */
export function main(argv: readonly string[] = process.argv.slice(2)): number {
    const parsed = parseArgs(argv);

    if (!parsed.ok) {
        console.error(`error: ${parsed.message}`);
        console.error('Run "stratumss help" for usage.');
        return 1;
    }

    const { options } = parsed;

    switch (options.command) {
        case 'help':
            console.log(HELP_TEXT);
            return 0;
        case 'version':
            console.log(getVersion());
            return 0;
        case 'list':
            return runList(options);
        case 'build':
            if (options.watch) {
                return runWatch(options);
            } else {
                const stats = buildOnce(options, true);
                return stats === null ? 1 : 0;
            }
    }
}

/** True when this file was executed directly rather than imported. */
function isEntryPoint(): boolean {
    const script = process.argv[1];
    if (script === undefined) return false;

    const self = fileURLToPath(import.meta.url);
    try {
        return fs.realpathSync(script) === fs.realpathSync(self);
    } catch {
        return path.resolve(script) === path.resolve(self);
    }
}

if (isEntryPoint()) {
    try {
        process.exitCode = main();
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`StratumSS error: ${message}`);
        process.exitCode = 1;
    }
}

export { DEFAULT_EXTENSIONS, DEFAULT_IGNORED_DIRECTORIES };
