#!/usr/bin/env node
/**
 * Builds the value-free stylesheet, for use without Node or a build step.
 *
 * `stratumss build` emits only the classes a project uses, which needs Node. This
 * script instead emits every utility that carries no value — enum utilities and
 * their aliases (`flex`, `absolute`, `text-center`, `items-vertical-center`) — so a
 * page can link a stylesheet and get the layout, sizing, colour-keyword and
 * typography vocabulary of the framework.
 *
 * What is deliberately *not* here: utilities whose name contains the value
 * (`padding-16px`, `color-#0f172a`). There are infinitely many of them, and picking
 * a fixed subset would mean inventing a spacing scale the compiler does not have.
 * Those classes need `npx stratumss build`.
 *
 * Usage: npm run cdn          build cdn/stratum.css and cdn/stratum.min.css
 *        npm run cdn -- --check  exit non-zero if the committed files are stale
 */

import fs from 'fs';
import path from 'path';
import zlib from 'zlib';
import { fileURLToPath } from 'url';

import { DEFINITIONS, generateCSS, parseClass } from '../dist/index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const outputDir = path.join(root, 'cdn');
const checkOnly = process.argv.includes('--check');
const version = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;

const names = new Set();

for (const definition of DEFINITIONS) {
    if (definition.kind === 'enum') {
        for (const value of definition.values ?? []) {
            names.add(`${definition.name}-${value}`);
        }
    }
    // Aliases are spelled-out names for a fixed value, so they are value-free too.
    for (const alias of Object.keys(definition.aliases ?? {})) {
        names.add(alias);
    }
}

const parsed = [...names].map(name => {
    try {
        return parseClass(name);
    } catch (error) {
        throw new Error(`${name}: ${error.message}`, { cause: error });
    }
});

const banner = `/*! StratumSS v${version} — the ${parsed.length} value-free utilities.
    Link this for prototypes; run \`npx stratumss build\` for production, which also
    emits the utilities that carry a value (padding-16px, color-#0f172a, …).
    Generated by scripts/build-cdn.mjs from the compiler's utility table. Do not edit. */`;

const outputs = [
    ['stratum.css', generateCSS(parsed, { header: banner })],
    ['stratum.min.css', generateCSS(parsed, { header: banner, minify: true })]
];

let stale = 0;

for (const [name, css] of outputs) {
    const file = path.join(outputDir, name);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;

    if (current !== css) {
        stale += 1;
        if (checkOnly) {
            console.error(`cdn/${name} is out of date — run npm run cdn`);
            continue;
        }
        fs.mkdirSync(outputDir, { recursive: true });
        fs.writeFileSync(file, css);
    }

    const gzip = zlib.gzipSync(css).length;
    console.log(`  cdn/${name.padEnd(15)} ${String(css.length).padStart(6)} B  ${String(gzip).padStart(5)} B gzipped  ${current === null ? 'written' : current === css ? 'unchanged' : 'updated'}`);
}

if (checkOnly && stale > 0) {
    process.exitCode = 1;
} else if (!checkOnly) {
    console.log(`StratumSS wrote ${parsed.length} value-free utilities to cdn/.`);
}
