#!/usr/bin/env node
/**
 * Generates docs/utilities.md from the compiler's own utility table, so the
 * documentation can never drift away from what the compiler actually accepts.
 *
 * Usage: npm run docs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { DEFINITIONS } from '../dist/index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const outputFile = path.join(here, '..', 'docs', 'utilities.md');

const kindExample = {
    enum: '`center`',
    length: '`16px`',
    number: '`1`',
    integer: '`1`',
    color: '`#3b82f6`',
    keyword: '`pointer`',
    raw: '`1px_solid_red`'
};

const groups = new Map();
for (const definition of DEFINITIONS) {
    const list = groups.get(definition.group) ?? [];
    list.push(definition);
    groups.set(definition.group, list);
}

const lines = [
    '# StratumSS utilities',
    '',
    '<!-- Generated by scripts/generate-docs.mjs — do not edit by hand. -->',
    '',
    `Every utility below is understood by \`stratumss\`. There are ${DEFINITIONS.length} utility families in ${groups.size} groups.`,
    '',
    'Write a class by joining the utility name to a value with a hyphen:',
    '`padding-16px`, `color-#3b82f6`, `items-vertical-center`.',
    '',
    'Values are validated at build time, so a typo such as `padding-4p` fails the build',
    'instead of silently producing a broken stylesheet.',
    ''
];

for (const [group, definitions] of groups) {
    lines.push(`## ${group}`, '');
    lines.push('| Class | CSS | Values |', '| --- | --- | --- |');

    for (const definition of definitions.sort((a, b) => a.name.localeCompare(b.name))) {
        // Pipes inside a markdown table cell must be escaped.
        const pattern = definition.kind === 'enum'
            ? `\`${definition.name}-<${(definition.values ?? []).join(' \\| ')}>\``
            : `\`${definition.name}-<${definition.kind}>\`  ${kindExample[definition.kind] ?? ''}`;
        const aliases = Object.keys(definition.aliases ?? {}).sort();
        const prefixAliases = Object.keys(definition.prefixAliases ?? {}).sort();
        const aliasNote = [
            ...aliases.map(alias => `\`${alias}\``),
            ...prefixAliases.map(alias => `\`${alias}<…>\``)
        ];

        lines.push(`| ${pattern} | \`${definition.property}\` | ${aliasNote.join(' ') || '—'} |`);
    }

    lines.push('');
}

lines.push(
    '## Value syntax',
    '',
    '| Syntax | Meaning | Example |',
    '| --- | --- | --- |',
    '| `-<value>` | A literal value | `width-437px` |',
    '| `-<a>_<b>` | Two values, joined by a space | `padding-10px_20px` |',
    '| `-neg-<value>` | A negative value, where CSS allows one | `margin-left-neg-4px` |',
    '| `<class>!` | Marks the declaration `!important` | `color-black!` |',
    '| `var(--x)`, `calc(…)` | Passed through untouched | `width-var(--w)` |',
    '',
    '## Groups',
    ''
);

for (const group of groups.keys()) {
    lines.push(`- ${group}`);
}
lines.push('');

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, lines.join('\n'), 'utf-8');

console.log(`Wrote ${path.relative(process.cwd(), outputFile)} (${DEFINITIONS.length} utilities).`);
